---
- name: Finalize the deploy
  deploy_helper: path={{ deploy_helper.project_path }} release={{ deploy_helper.new_release }} state=finalize keep_releases=20

- name: reload php-fpm
  service: name=php7.0-fpm state=reloaded
  when: "'app' in group_names"
  tags:
    - env
