---
- name: git clone
  local_action:
    module: git
    repo: "git@git.corp.angejia.com:account/account.git"
    depth: 1
    dest: "{{ account_localpath }}"
    version: "{{ account_version }}"
    reference: "account/"

- name: composer install
  local_action:
    module: composer
    no_dev: yes
    working_dir: "{{ account_localpath }}"

- name: mkdir for node_modules history
  local_action:
    module: file
    path: cache/account.node/
    state: directory
    mode: 0755
  when: backend is undefined

- name: copy node_modules for history
  local_action:
    module: shell rsync -a cache/account.node/ {{ account_localpath }}/node_modules
  when: backend is undefined

- name: npm install
  local_action:
    module: npm
    production: yes
    registry: http://registry.npm.taobao.org
    path: "{{ account_localpath }}"
  when: backend is undefined

- name: copy node_modules to history
  local_action:
    module: shell rsync -a {{ account_localpath }}/node_modules/ cache/account.node --delete
  when: backend is undefined

- name: npm deploy
  local_action:
    module: command npm run-script deploy
    chdir: "{{ account_localpath }}"
  when: backend is undefined
