---
- name: copy file from previous_release
  synchronize:
    src: "{{ deploy_helper.previous_release_path }}/"
    dest: "{{ deploy_helper.new_release_path }}/"
    partial: true
  delegate_to: "{{ inventory_hostname }}"
  when: "backend is defined and (deploy_helper.previous_release != deploy_helper.new_release)"

- synchronize:
    src: "{{ retrx_mgt_localpath }}/"
    dest: "{{ deploy_helper.new_release_path }}/"
    partial: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=node_modules"
      - "--chown=www-data:www-data"

- name: set version
  copy: >
    content={{ retrx_mgt_version }} dest={{ deploy_helper.new_release_path }}/public/version
    owner=www-data group=www-data

- name: copy dotenv file
  copy: src=.env.retrx-mgt dest={{ deploy_helper.shared_path }}/.env.retrx-mgt
  tags:
    - env

- name: symlink dotenv file
  file: >
    src={{ deploy_helper.shared_path }}/.env.retrx-mgt dest={{ deploy_helper.new_release_path }}/.env
    state=link
